FROM ubuntu:24.04

COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

RUN set -eux; \
    sed -i 's|http://archive.ubuntu.com/ubuntu|https://archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources; \
    sed -i 's|http://security.ubuntu.com/ubuntu|https://security.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        bison \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        flex \
        git \
        libaio-dev \
        libbluetooth-dev \
        libbrlapi-dev \
        libbz2-dev \
        libcap-ng-dev \
        libcapstone-dev \
        libcurl4-gnutls-dev \
        libdw-dev \
        libelf-dev \
        libfdt-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libibverbs-dev \
        libiscsi-dev \
        libjpeg8-dev \
        liblzo2-dev \
        libncurses-dev \
        libnfs-dev \
        libnuma-dev \
        libpcap-dev \
        libpixman-1-dev \
        librbd-dev \
        librdmacm-dev \
        libsasl2-dev \
        libsdl2-dev \
        libseccomp-dev \
        libsnappy-dev \
        libssh-dev \
        libtraceevent-dev \
        libunwind-dev \
        libvde-dev \
        libvdeplug-dev \
        libvte-2.91-dev \
        libxen-dev \
        ninja-build \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-tomli \
        python3-wheel \
        rsync \
        valgrind \
        wget \
        xfslibs-dev \
        zlib1g-dev; \
    rm -rf /var/lib/apt/lists/*


RUN git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git && \
    cd linux/tools/perf && \
    NO_JEVENTS=1 make && \
    cp perf /usr/bin && \
    cd / && rm -rf linux

# Install Python 2.7 for compatibility with QEMU's build system. 
# We need to use an older Python version because QEMU's build system is not compatible with 
# Python 3.
RUN wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz && \
    tar -xzf Python-2.7.18.tgz && \
    cd Python-2.7.18 && \
    ./configure --prefix=/opt/python2.7 && \
    make && \
    make install && \
    ln -s /opt/python2.7/bin/python2.7 /usr/local/bin/python2.7 && \
    cd / && rm -rf Python-2.7.18 Python-2.7.18.tgz

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

# 2. Setup paths
WORKDIR /app

COPY openssl_pipeline.py common.py project.py logger.py config.yaml /app/

CMD ["python3", "openssl_pipeline.py"]
