FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev python3-pip libncurses-dev libtool libtool-bin\
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

# 2. Setup paths
WORKDIR /app
#RUN mkdir -p /app/inputs \
#    && mkdir -p /app/output

# 3. Git fix
# RUN git config --global --add safe.directory '*'

# 4. Remove default perf wrapper
# RUN rm -f /usr/bin/perf

# ------------------------------------------------------------------
# DOWNLOAD RESOURCES
# ------------------------------------------------------------------

# Download OpenSSL Repo to /app/inputs/openssl
#RUN git clone https://github.com/openssl/openssl.git /app/inputs/openssl

# ------------------------------------------------------------------

COPY openssl_pipeline.py config.py common.py project.py config.yaml /app/

CMD ["python3", "openssl_pipeline.py"]