FROM mwk-energy-base:1.0

RUN apt-get update && apt-get install -y \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

#ENV DEBIAN_FRONTEND=noninteractive
#
## 1. Install Dependencies (Optimized for OpenSSL)
#RUN apt-get update && apt-get install -y \
#    build-essential \
#    pkg-config \
#    git \
#    python3 \
#    linux-tools-common \
#    rsync \
#    wget \
#    curl \
#    # perl 
#    # libslang2 \
#    # libunwind8 \
#    # liblzma5 \
#    # libnuma1 \
#    # libelf1 \
#    # libdw1 \
#    # libzstd1 \
#    # libdebuginfod1 \
#    # libpfm4 \
#    # libpython3.12 \
#    # libperl5.38 \
#    # libtraceevent1 \
#    # libbabeltrace1 \
#    # && rm -rf /var/lib/apt/lists/*
#
# 2. Setup paths
WORKDIR /app
#RUN mkdir -p /app/inputs \
#    && mkdir -p /app/output

# 3. Git fix
# RUN git config --global --add safe.directory '*'

# 4. Remove default perf wrapper
# RUN rm -f /usr/bin/perf

# ------------------------------------------------------------------
# DOWNLOAD RESOURCES
# ------------------------------------------------------------------

# Download OpenSSL Repo to /app/inputs/openssl
RUN git clone https://github.com/openssl/openssl.git /app/inputs/openssl

# ------------------------------------------------------------------

COPY openssl_pipeline.py /app/

CMD ["python3", "openssl_pipeline.py"]